<a href="https://colab.research.google.com/github/MetalHeadv3/data-science/blob/main/R%C3%B3wnanie%20macierze.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[2, 4], [1, -1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [3]:
B = np.array([[10], [-1]])
B

array([[10],
       [-1]])

In [5]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [6]:
X.shape

(2, 1)