<a href="https://colab.research.google.com/github/MetalHeadv3/data-science/blob/main/tablice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

tworzenie tablic

In [ ]:
import numpy as np

In [ ]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Operacje na tabliach



In [ ]:
A = np.array([3, 1, 5, 6])
B = np.array([3, 5, -1, 2])
print(A)
print(B)

[3 1 5 6]
[ 3  5 -1  2]


In [ ]:
A+B

array([6, 6, 4, 8])

In [ ]:
A/B

array([ 1. ,  0.2, -5. ,  3. ])

In [ ]:
X = np.array([[1, 3], [2, 5]])
Y = np.array ([[1, -4], [3, 6]])
print(X, '\n')
print(Y)

[[1 3]
 [2 5]] 

[[ 1 -4]
 [ 3  6]]


In [ ]:
X*Y

array([[  1, -12],
       [  6,  30]])

In [ ]:
np.dot(X, Y)

array([[10, 14],
       [17, 22]])

In [ ]:
X.dot(Y)

array([[10, 14],
       [17, 22]])

Liczby pseudolosowe

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
np.random.randn()

0.386902497859262

In [ ]:
np.random.randint(10)

9

In [ ]:
np.random.randint(low=10, high= 1250, size = 5 )

array([ 787,  439,  209, 1095,  351])

In [ ]:
np.random.choice(['chuj', 'cwel', 'nigg'])


'cwel'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([1, 2, 7, 3, 9, 5, 8, 4, 6, 0])

Podstawowe funkcje

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.exp(15)

3269017.3724721107

In [ ]:
np.sqrt(9) 

3.0

In [ ]:
np.all([2, 3, 1])

True

In [ ]:
np.any([0, 0, 0])

False

In [ ]:
A= np.random.randn(5)
A

array([-1.55602368, -0.05446484, -1.81127879, -0.63117522, -0.92815918])

In [ ]:
np.argmax(A)

1

In [ ]:
A[np.argmax(A)]

-0.05446484378125436

In [ ]:
np.argmin(A)

2

In [ ]:
A[np.argmin(A)]

-1.8112787909180463

In [ ]:
np.argsort(A)

array([2, 0, 4, 3, 1])

In [ ]:
np.min(A)

-1.8112787909180463

In [ ]:
np.mean(A)

-0.9962203429425323

In [ ]:
np.median(A)

-0.928159184570213

In [ ]:
np.std(A)

0.6328497028717766